# CMake generated Testfile for 
# Source directory: /mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/examples/socket
# Build directory: /mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/cmake-cache/examples/socket
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-socket-bound-static-routing "ns3.42-socket-bound-static-routing-default")
set_tests_properties(ctest-socket-bound-static-routing PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build/examples/socket/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/macros-and-definitions.cmake;1424;build_exec;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/examples/socket/CMakeLists.txt;1;build_example;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/examples/socket/CMakeLists.txt;0;")
add_test(ctest-socket-bound-tcp-static-routing "ns3.42-socket-bound-tcp-static-routing-default")
set_tests_properties(ctest-socket-bound-tcp-static-routing PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build/examples/socket/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/macros-and-definitions.cmake;1424;build_exec;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/examples/socket/CMakeLists.txt;11;build_example;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/examples/socket/CMakeLists.txt;0;")
add_test(ctest-socket-options-ipv4 "ns3.42-socket-options-ipv4-default")
set_tests_properties(ctest-socket-options-ipv4 PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build/examples/socket/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/macros-and-definitions.cmake;1424;build_exec;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/examples/socket/CMakeLists.txt;22;build_example;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/examples/socket/CMakeLists.txt;0;")
add_test(ctest-socket-options-ipv6 "ns3.42-socket-options-ipv6-default")
set_tests_properties(ctest-socket-options-ipv6 PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build/examples/socket/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/macros-and-definitions.cmake;1424;build_exec;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/examples/socket/CMakeLists.txt;32;build_example;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/examples/socket/CMakeLists.txt;0;")
