# CMake generated Testfile for 
# Source directory: /mnt/d/Downloads/ns-3-dev/src/tap-bridge/examples
# Build directory: /mnt/d/Downloads/ns-3-dev/cmake-cache/src/tap-bridge/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-tap-csma "ns3.42-tap-csma-default")
set_tests_properties(ctest-tap-csma PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/ns-3-dev/build/src/tap-bridge/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/ns-3-dev/src/tap-bridge/examples/CMakeLists.txt;2;build_lib_example;/mnt/d/Downloads/ns-3-dev/src/tap-bridge/examples/CMakeLists.txt;0;")
add_test(ctest-tap-csma-virtual-machine "ns3.42-tap-csma-virtual-machine-default")
set_tests_properties(ctest-tap-csma-virtual-machine PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/ns-3-dev/build/src/tap-bridge/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/ns-3-dev/src/tap-bridge/examples/CMakeLists.txt;12;build_lib_example;/mnt/d/Downloads/ns-3-dev/src/tap-bridge/examples/CMakeLists.txt;0;")
add_test(ctest-tap-wifi-virtual-machine "ns3.42-tap-wifi-virtual-machine-default")
set_tests_properties(ctest-tap-wifi-virtual-machine PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/ns-3-dev/build/src/tap-bridge/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/ns-3-dev/src/tap-bridge/examples/CMakeLists.txt;21;build_lib_example;/mnt/d/Downloads/ns-3-dev/src/tap-bridge/examples/CMakeLists.txt;0;")
add_test(ctest-tap-wifi-dumbbell "ns3.42-tap-wifi-dumbbell-default")
set_tests_properties(ctest-tap-wifi-dumbbell PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/ns-3-dev/build/src/tap-bridge/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/ns-3-dev/src/tap-bridge/examples/CMakeLists.txt;32;build_lib_example;/mnt/d/Downloads/ns-3-dev/src/tap-bridge/examples/CMakeLists.txt;0;")
