# CMake generated Testfile for 
# Source directory: /mnt/d/Downloads/ns-3-dev/scratch
# Build directory: /mnt/d/Downloads/ns-3-dev/cmake-cache/scratch
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-scratch_nr-prose-unicast-single-link-modified-1 "ns3.42-nr-prose-unicast-single-link-modified-1-default")
set_tests_properties(ctest-scratch_nr-prose-unicast-single-link-modified-1 PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/ns-3-dev/build/scratch/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/ns-3-dev/scratch/CMakeLists.txt;67;build_exec;/mnt/d/Downloads/ns-3-dev/scratch/CMakeLists.txt;79;create_scratch;/mnt/d/Downloads/ns-3-dev/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_nr-prose-unicast-single-link-modified-org "ns3.42-nr-prose-unicast-single-link-modified-org-default")
set_tests_properties(ctest-scratch_nr-prose-unicast-single-link-modified-org PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/ns-3-dev/build/scratch/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/ns-3-dev/scratch/CMakeLists.txt;67;build_exec;/mnt/d/Downloads/ns-3-dev/scratch/CMakeLists.txt;79;create_scratch;/mnt/d/Downloads/ns-3-dev/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_nr-prose-unicast-single-link-modified "ns3.42-nr-prose-unicast-single-link-modified-default")
set_tests_properties(ctest-scratch_nr-prose-unicast-single-link-modified PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/ns-3-dev/build/scratch/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/ns-3-dev/scratch/CMakeLists.txt;67;build_exec;/mnt/d/Downloads/ns-3-dev/scratch/CMakeLists.txt;79;create_scratch;/mnt/d/Downloads/ns-3-dev/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_nr-prose-unicast-single-link "ns3.42-nr-prose-unicast-single-link-default")
set_tests_properties(ctest-scratch_nr-prose-unicast-single-link PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/ns-3-dev/build/scratch/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/ns-3-dev/scratch/CMakeLists.txt;67;build_exec;/mnt/d/Downloads/ns-3-dev/scratch/CMakeLists.txt;79;create_scratch;/mnt/d/Downloads/ns-3-dev/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_scratch-simulator "ns3.42-scratch-simulator-default")
set_tests_properties(ctest-scratch_scratch-simulator PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/ns-3-dev/build/scratch/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/ns-3-dev/scratch/CMakeLists.txt;67;build_exec;/mnt/d/Downloads/ns-3-dev/scratch/CMakeLists.txt;79;create_scratch;/mnt/d/Downloads/ns-3-dev/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_ues "ns3.42-ues-default")
set_tests_properties(ctest-scratch_ues PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/ns-3-dev/build/scratch/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/ns-3-dev/scratch/CMakeLists.txt;67;build_exec;/mnt/d/Downloads/ns-3-dev/scratch/CMakeLists.txt;79;create_scratch;/mnt/d/Downloads/ns-3-dev/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_subdir_scratch-subdir "ns3.42-scratch-subdir-default")
set_tests_properties(ctest-scratch_subdir_scratch-subdir PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/ns-3-dev/build/scratch/subdir/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/ns-3-dev/scratch/CMakeLists.txt;67;build_exec;/mnt/d/Downloads/ns-3-dev/scratch/CMakeLists.txt;109;create_scratch;/mnt/d/Downloads/ns-3-dev/scratch/CMakeLists.txt;0;")
subdirs("nested-subdir")
