# CMake generated Testfile for 
# Source directory: /mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/contrib/nr-prose/examples
# Build directory: /mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/cmake-cache/contrib/nr-prose/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-nr-prose-unicast-single-link "ns3.42-nr-prose-unicast-single-link-default")
set_tests_properties(ctest-nr-prose-unicast-single-link PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build/contrib/nr-prose/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/contrib/nr-prose/examples/CMakeLists.txt;17;build_lib_example;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/contrib/nr-prose/examples/CMakeLists.txt;0;")
add_test(ctest-nr-prose-discovery "ns3.42-nr-prose-discovery-default")
set_tests_properties(ctest-nr-prose-discovery PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build/contrib/nr-prose/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/contrib/nr-prose/examples/CMakeLists.txt;17;build_lib_example;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/contrib/nr-prose/examples/CMakeLists.txt;0;")
add_test(ctest-nr-prose-discovery-l3-relay "ns3.42-nr-prose-discovery-l3-relay-default")
set_tests_properties(ctest-nr-prose-discovery-l3-relay PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build/contrib/nr-prose/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/contrib/nr-prose/examples/CMakeLists.txt;17;build_lib_example;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/contrib/nr-prose/examples/CMakeLists.txt;0;")
add_test(ctest-nr-prose-discovery-l3-relay-selection "ns3.42-nr-prose-discovery-l3-relay-selection-default")
set_tests_properties(ctest-nr-prose-discovery-l3-relay-selection PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build/contrib/nr-prose/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/contrib/nr-prose/examples/CMakeLists.txt;17;build_lib_example;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/contrib/nr-prose/examples/CMakeLists.txt;0;")
add_test(ctest-nr-prose-unicast-multi-link "ns3.42-nr-prose-unicast-multi-link-default")
set_tests_properties(ctest-nr-prose-unicast-multi-link PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build/contrib/nr-prose/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/contrib/nr-prose/examples/CMakeLists.txt;28;build_lib_example;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/contrib/nr-prose/examples/CMakeLists.txt;0;")
add_test(ctest-nr-prose-unicast-l3-relay "ns3.42-nr-prose-unicast-l3-relay-default")
set_tests_properties(ctest-nr-prose-unicast-l3-relay PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build/contrib/nr-prose/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/contrib/nr-prose/examples/CMakeLists.txt;28;build_lib_example;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/contrib/nr-prose/examples/CMakeLists.txt;0;")
add_test(ctest-nr-prose-network-coex "ns3.42-nr-prose-network-coex-default")
set_tests_properties(ctest-nr-prose-network-coex PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build/contrib/nr-prose/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/contrib/nr-prose/examples/CMakeLists.txt;28;build_lib_example;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/contrib/nr-prose/examples/CMakeLists.txt;0;")
add_test(ctest-nr-prose-l3-relay "ns3.42-nr-prose-l3-relay-default")
set_tests_properties(ctest-nr-prose-l3-relay PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build/contrib/nr-prose/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/contrib/nr-prose/examples/CMakeLists.txt;28;build_lib_example;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/contrib/nr-prose/examples/CMakeLists.txt;0;")
add_test(ctest-nr-prose-l3-relay-on-off "ns3.42-nr-prose-l3-relay-on-off-default")
set_tests_properties(ctest-nr-prose-l3-relay-on-off PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build/contrib/nr-prose/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/contrib/nr-prose/examples/CMakeLists.txt;42;build_lib_example;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/contrib/nr-prose/examples/CMakeLists.txt;0;")
