# CMake generated Testfile for 
# Source directory: /mnt/d/Downloads/ns-3-dev/src/sixlowpan/examples
# Build directory: /mnt/d/Downloads/ns-3-dev/cmake-cache/src/sixlowpan/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-example-sixlowpan "ns3.42-example-sixlowpan-default")
set_tests_properties(ctest-example-sixlowpan PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/ns-3-dev/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/ns-3-dev/src/sixlowpan/examples/CMakeLists.txt;1;build_lib_example;/mnt/d/Downloads/ns-3-dev/src/sixlowpan/examples/CMakeLists.txt;0;")
add_test(ctest-example-ping-lr-wpan "ns3.42-example-ping-lr-wpan-default")
set_tests_properties(ctest-example-ping-lr-wpan PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/ns-3-dev/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/ns-3-dev/src/sixlowpan/examples/CMakeLists.txt;12;build_lib_example;/mnt/d/Downloads/ns-3-dev/src/sixlowpan/examples/CMakeLists.txt;0;")
add_test(ctest-example-ping-lr-wpan-beacon "ns3.42-example-ping-lr-wpan-beacon-default")
set_tests_properties(ctest-example-ping-lr-wpan-beacon PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/ns-3-dev/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/ns-3-dev/src/sixlowpan/examples/CMakeLists.txt;23;build_lib_example;/mnt/d/Downloads/ns-3-dev/src/sixlowpan/examples/CMakeLists.txt;0;")
add_test(ctest-example-ping-lr-wpan-mesh-under "ns3.42-example-ping-lr-wpan-mesh-under-default")
set_tests_properties(ctest-example-ping-lr-wpan-mesh-under PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/ns-3-dev/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/ns-3-dev/src/sixlowpan/examples/CMakeLists.txt;34;build_lib_example;/mnt/d/Downloads/ns-3-dev/src/sixlowpan/examples/CMakeLists.txt;0;")
