# CMake generated Testfile for 
# Source directory: /mnt/d/Downloads/ns-3-dev/src/wifi/examples
# Build directory: /mnt/d/Downloads/ns-3-dev/cmake-cache/src/wifi/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-wifi-phy-test "ns3.42-wifi-phy-test-default")
set_tests_properties(ctest-wifi-phy-test PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/ns-3-dev/build/src/wifi/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/ns-3-dev/src/wifi/examples/CMakeLists.txt;1;build_lib_example;/mnt/d/Downloads/ns-3-dev/src/wifi/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-test-interference-helper "ns3.42-wifi-test-interference-helper-default")
set_tests_properties(ctest-wifi-test-interference-helper PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/ns-3-dev/build/src/wifi/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/ns-3-dev/src/wifi/examples/CMakeLists.txt;11;build_lib_example;/mnt/d/Downloads/ns-3-dev/src/wifi/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-manager-example "ns3.42-wifi-manager-example-default")
set_tests_properties(ctest-wifi-manager-example PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/ns-3-dev/build/src/wifi/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/ns-3-dev/src/wifi/examples/CMakeLists.txt;21;build_lib_example;/mnt/d/Downloads/ns-3-dev/src/wifi/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-trans-example "ns3.42-wifi-trans-example-default")
set_tests_properties(ctest-wifi-trans-example PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/ns-3-dev/build/src/wifi/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/ns-3-dev/src/wifi/examples/CMakeLists.txt;33;build_lib_example;/mnt/d/Downloads/ns-3-dev/src/wifi/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-phy-configuration "ns3.42-wifi-phy-configuration-default")
set_tests_properties(ctest-wifi-phy-configuration PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/ns-3-dev/build/src/wifi/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/ns-3-dev/src/wifi/examples/CMakeLists.txt;45;build_lib_example;/mnt/d/Downloads/ns-3-dev/src/wifi/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-bianchi "ns3.42-wifi-bianchi-default")
set_tests_properties(ctest-wifi-bianchi PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/ns-3-dev/build/src/wifi/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/ns-3-dev/src/wifi/examples/CMakeLists.txt;52;build_lib_example;/mnt/d/Downloads/ns-3-dev/src/wifi/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-phy-rx-trace-example "ns3.42-wifi-phy-rx-trace-example-default")
set_tests_properties(ctest-wifi-phy-rx-trace-example PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/ns-3-dev/build/src/wifi/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/ns-3-dev/src/wifi/examples/CMakeLists.txt;61;build_lib_example;/mnt/d/Downloads/ns-3-dev/src/wifi/examples/CMakeLists.txt;0;")
