# CMake generated Testfile for 
# Source directory: /mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/src/csma/examples
# Build directory: /mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/cmake-cache/src/csma/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-csma-one-subnet "ns3.42-csma-one-subnet-default")
set_tests_properties(ctest-csma-one-subnet PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build/src/csma/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/src/csma/examples/CMakeLists.txt;11;build_lib_example;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/src/csma/examples/CMakeLists.txt;0;")
add_test(ctest-csma-broadcast "ns3.42-csma-broadcast-default")
set_tests_properties(ctest-csma-broadcast PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build/src/csma/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/src/csma/examples/CMakeLists.txt;11;build_lib_example;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/src/csma/examples/CMakeLists.txt;0;")
add_test(ctest-csma-packet-socket "ns3.42-csma-packet-socket-default")
set_tests_properties(ctest-csma-packet-socket PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build/src/csma/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/src/csma/examples/CMakeLists.txt;11;build_lib_example;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/src/csma/examples/CMakeLists.txt;0;")
add_test(ctest-csma-multicast "ns3.42-csma-multicast-default")
set_tests_properties(ctest-csma-multicast PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build/src/csma/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/src/csma/examples/CMakeLists.txt;11;build_lib_example;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/src/csma/examples/CMakeLists.txt;0;")
add_test(ctest-csma-raw-ip-socket "ns3.42-csma-raw-ip-socket-default")
set_tests_properties(ctest-csma-raw-ip-socket PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build/src/csma/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/src/csma/examples/CMakeLists.txt;21;build_lib_example;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/src/csma/examples/CMakeLists.txt;0;")
add_test(ctest-csma-ping "ns3.42-csma-ping-default")
set_tests_properties(ctest-csma-ping PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build/src/csma/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/src/csma/examples/CMakeLists.txt;31;build_lib_example;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/src/csma/examples/CMakeLists.txt;0;")
