# CMake generated Testfile for 
# Source directory: /mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/src/stats/examples
# Build directory: /mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/cmake-cache/src/stats/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-time-probe-example "ns3.42-time-probe-example-default")
set_tests_properties(ctest-time-probe-example PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build/src/stats/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/src/stats/examples/CMakeLists.txt;1;build_lib_example;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-gnuplot-example "ns3.42-gnuplot-example-default")
set_tests_properties(ctest-gnuplot-example PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build/src/stats/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/src/stats/examples/CMakeLists.txt;20;build_lib_example;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-double-probe-example "ns3.42-double-probe-example-default")
set_tests_properties(ctest-double-probe-example PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build/src/stats/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/src/stats/examples/CMakeLists.txt;20;build_lib_example;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-gnuplot-aggregator-example "ns3.42-gnuplot-aggregator-example-default")
set_tests_properties(ctest-gnuplot-aggregator-example PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build/src/stats/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/src/stats/examples/CMakeLists.txt;20;build_lib_example;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-gnuplot-helper-example "ns3.42-gnuplot-helper-example-default")
set_tests_properties(ctest-gnuplot-helper-example PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build/src/stats/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/src/stats/examples/CMakeLists.txt;20;build_lib_example;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-file-aggregator-example "ns3.42-file-aggregator-example-default")
set_tests_properties(ctest-file-aggregator-example PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build/src/stats/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/src/stats/examples/CMakeLists.txt;20;build_lib_example;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-file-helper-example "ns3.42-file-helper-example-default")
set_tests_properties(ctest-file-helper-example PROPERTIES  WORKING_DIRECTORY "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build/src/stats/examples/" _BACKTRACE_TRIPLES "/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;47;add_test;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/src/stats/examples/CMakeLists.txt;20;build_lib_example;/mnt/d/Downloads/BTP-D2D-Networks/ns-3-dev/src/stats/examples/CMakeLists.txt;0;")
